apiVersion: v1
kind: Service
metadata:
  name: flask-sql-app-service
spec:
  selector:
    app: flask-sql-app
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 8080  # Container port
  type: LoadBalancer  # Expose app outside the cluster using a load balancer
